version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    hostname: redis
    networks:
      - spring-cloud-network
  producer-service:
    build:
      context: Redis-Producer
      dockerfile: Dockerfile
    image: producer-service:latest
    ports:
      - 9092:9092
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge